services:
  - type: web
    name: cliniaura-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://alamandahasitha:9502072613@cluster0.kjzfjen.mongodb.net/cliniaura

  - type: web
    name: cliniaura-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: cliniaura-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
